# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "Serein/Console/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "nuget"
    directory: "Serein/Console_For_Unix/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "nuget"
    directory: "Serein/Winform/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "nuget"
    directory: "Serein/WPF/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "WPF-UI"
        versions:
          - "2.0.*" # 暂时不更新依赖

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
