name-template: 'v$RESOLVED_VERSION'
tag-prefix: 'v'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 新功能'
    labels:
      - 'feat'
      - 'feature'
      - 'enhancement'
  - title: '🐛 修复'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 其他'
    label:
      - 'chore'
      - 'docs'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' 
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes
  ### 🚀 新功能

  ### 🐛 修复

  ### 📃 文档

  ### 🧰 其他
