name-template: 'v$RESOLVED_VERSION'
tag-prefix: 'v'
tag-template: 'v$RESOLVED_VERSION'
template: |
  ## Main Changes in v$RESOLVED_VERSION

  >查看 **[✨完整更新日志](http://serein.cc/#/Versions/v$RESOLVED_VERSION)**
  
  ---
  ![GitHub release (latest by date)](https://img.shields.io/github/downloads/Zaitonn/Serein/v$RESOLVED_VERSION/total?style=for-the-badge)
  > 推荐阅读：[如何选择不同的版本](https://serein.cc/#/Tutorial/DifferentVersions)
