name: Build

on:
  push:
  pull_request:

jobs:
    Build:
      runs-on: windows-latest

      steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Upload Serein codes
        uses: actions/upload-artifact@v3
        with:
          name: Code
          path: |
            ${{ github.workspace }}
            !.git/

      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.202

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'

      - name: NuGet restore
        run: nuget restore

      - name: Build the solution(Debug)
        run: msbuild /p:Configuration=$env:Configuration
        env:
          Configuration: Debug

      - name: Upload Serein(Debug)
        uses: actions/upload-artifact@v3
        with:
          name: Serein_Debug
          path: ${{ github.workspace }}\bin\Debug

      - name: Build the solution(Release)
        run: msbuild /p:Configuration=$env:Configuration
        env:
          Configuration: Release

      - name: Upload Serein(Release)
        uses: actions/upload-artifact@v3
        with:
          name: Serein_Release
          path: ${{ github.workspace }}\bin\Release