name: Code Scanning

on:
  push:
    paths:
      - '**.cs'
  pull_request:

jobs:
  CodeQL-Build:
    runs-on: windows-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: csharp

      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.202

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'

      - name: NuGet restore
        run: nuget restore

      - name: Build the solution
        run: msbuild /p:Configuration=$env:Configuration /p:UseSharedCompilation=false
        env:
          Configuration: Debug

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
